Repository flooding-kr/flooding-app-designSystem, pull requests merged in 2025-01, with the labels that each got.

#11 🔀 :: (#10)-Flutter Master CI 수정
  .github/workflows/flutter_master_ci.yml
Labels: 0️⃣ Priority: High, 🐞 Bug

#12 🔀 :: (#10) Color 디자인 시스템 추가, 패키지 구현 디렉토리 분리
  .github/workflows/flutter_master_ci.yml
  .idea/.gitignore
  .idea/other.xml
  .metadata
  CHANGELOG.md
  LICENSE
  README.md
  lib/flooding_app_design_system.dart
  lib/src/color.dart
  lib/src/typography.dart
  pub_login.sh
  pubspec.yaml
  test/design_system_test.dart
  test/flooding_app_design_system_test.dart
Labels: 1️⃣ Priority: Medium, ♻️ Refactor, ✨ Feature, 📝 Docs

#17 🔀 :: (#13) ci release 중복 해결
  .github/CODEOWNERS
  .github/workflows/flutter_master_ci.yml
Labels: 2️⃣ Priority: Low, ♻️ Refactor

#25 🔀 :: (#21) - update to automatically tag discord users when creating pr #22
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/flutter_develop_ci.yml
  .github/workflows/flutter_master_ci.yml
  .idea/.gitignore
  .idea/other.xml
  .metadata
  CHANGELOG.md
  LICENSE
  README.md
  lib/flooding_app_design_system.dart
  lib/src/color.dart
  lib/src/typography.dart
  pub_login.sh
  pubspec.yaml
  test/design_system_test.dart
  test/flooding_app_design_system_test.dart
Labels: 📝 Docs
